spring:
  batch:
    job:
      enabled: false

  shell:
    interactive:
      enabled: true

  data:
    mmongodb:
      port: 27017
      host: localhost
      database: awesomeMongo

  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto:
    show-sql: true

  h2:
    console:
      enabled: true

  liquibase:
    enabled: true

  output:
    ansi:
      enabled: always
  mongodb:
    embedded:
      version:


logging:
  level:
    root: ERROR

mongock:
  #runner-type: "ApplicationRunner" # default
  runner-type: "InitializingBean"
  change-logs-scan-package:
    - ru.otus.spring.homework_26.mongock.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local