POST http://localhost:8080/login
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="username"

{{username}}
--WebAppBoundary--
Content-Disposition: form-data; name="password"

{{password}}
--WebAppBoundary--

###

GET http://localhost:8080/actuator
Accept: application/json

###

###

GET http://localhost:8080/actuator/env
Accept: application/json

###