--liquibase formatted sql

--changeset nikolskiy:2021-10-04--0010-create-tables
DROP TABLE IF EXISTS AUTHORS CASCADE;
--changeset nikolskiy:2021-10-04--0011-create-tables
create table authors
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name varchar(255),
    primary key (id)
);
--changeset nikolskiy:2021-10-04--0012-create-tables
DROP TABLE IF EXISTS GENRE CASCADE;
--changeset nikolskiy:2021-10-04--0013-create-tables
CREATE TABLE GENRE
(
    ID   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME VARCHAR(255)
);
--changeset nikolskiy:2021-10-04--0014-create-tables
DROP TABLE IF EXISTS BOOKS;
--changeset nikolskiy:2021-10-04--0015-create-tables
CREATE TABLE BOOKS
(
    ID        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME      VARCHAR(255),
    AUTHOR_ID BIGINT,
    GENRE_ID  BIGINT,
    FOREIGN KEY (AUTHOR_ID)
        REFERENCES AUTHORS (ID),
    FOREIGN KEY (GENRE_ID)
        REFERENCES GENRE (ID)
);
--changeset nikolskiy:2021-10-13--0016-create-tables
DROP TABLE IF EXISTS COMMENTS CASCADE;
--changeset nikolskiy:2021-10-13--0017-create-tables
CREATE TABLE COMMENTS
(
    ID         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NAME       VARCHAR(255),
    DT_CREATED timestamp,
    BOOK_ID    bigint,
    FOREIGN KEY (BOOK_ID)
        REFERENCES BOOKS (ID)
        ON DELETE CASCADE
);