apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: contino
spec:
  replicas: 3
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres
          imagePullPolicy: 'IfNotPresent'
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: db
          envFrom:
            - secretRef:
                name: postgres-secret